### ISSUE TITLE
can i get requested fields in resolve

### ISSUE THREAD

**Issue by sunhaolin** [moleculerjs/moleculer-apollo-server#111]
I found a npm package [graphql-parse-resolve-info](https://www.npmjs.com/package/graphql-parse-resolve-info)  to parses a GraphQLResolveInfo object into a tree of the fields.

May be in `createActionResolver` method  , add `resolveInfo` as the fourth param behind `root, args, context`,

https://github.com/moleculerjs/moleculer-apollo-server/blob/7f0e2e2e2cb8c3118aa19385025578b2e5d7526f/src/service.js#L152-L162

And then passed as meta to action, `return await context.ctx.call(actionName, mergedParams, { meta: { resolveInfo } });`

https://github.com/moleculerjs/moleculer-apollo-server/blob/7f0e2e2e2cb8c3118aa19385025578b2e5d7526f/src/service.js#L254

**Comment by shawnmcknight** [comment]
@sunhaolin Since `createActionResolver` is a mixin method, you can provide your own definition and behavior for what it does.  essentially you can override it to have the implementation you are looking for without a need to modify `moleculer-apollo-server`.  Please try that out and see if it works for you.

**Comment by sunhaolin** [comment]
@shawnmcknight works fine, thank you very mach!
