### ISSUE TITLE
More descriptive GQL Schema Errors

### ISSUE THREAD

**Issue by timsayshey** [moleculerjs/moleculer-apollo-server#46]
Configuring graphql with Moleculer is exteremly finicky. I keep getting `UNABLE_COMPILE_GRAPHQL_SCHEMA` errors. It would nice if the errors were more helpful. They could include more information about what the actual problem is.

**Comment by Hugome** [comment]
You can have the details of these compile error in the `data` of the `MoleculerServerError`.
And if you print log in your console with at least the error level, you will find in your console, the exception raised by the `graphql` module :
![image](https://user-images.githubusercontent.com/1301995/62402615-e396c780-b588-11e9-8534-466bc8e68cbc.png)
In the middle of the scree you have the SDL syntax error : 'Error: Unknown type "Stringd". Did you mean "String"?"

**Comment by shawnmcknight** [comment]
Also important to keep in mind is that `moleculer-apollo-server` is largely just fronting [apollo-server](https://github.com/apollographql/apollo-server) and [graphql-tools](https://github.com/apollographql/graphql-tools).  For instance, schema errors are not detected directly by `moleculer-apollo-server`, but rather are thrown from the `makeExecutableSchema` function from `graphql-tools`.  As @Hugome mentioned, those errors are being emitted in the thrown error from `moleculer-apollo-server`, but it's just passing along what `makeExecutableSchema` threw.  If you're finding that the errors aren't descriptive enough then raising an issue on that repo would probably be more appropriate since `moleculer-apollo-server` doesn't do any schema validations of its own.

**Comment by timsayshey** [comment]
Thank you @shawnmcknight and @Hugome - I've got things working now but I'm sure I'll use your answers for reference in the future
