### ISSUE TITLE
Need help to create pagination

### ISSUE THREAD

**Issue by Tautorn** [moleculerjs/moleculer-apollo-server#60]
Hi there.

I need help to create pagination to my queries. With page and page_size (limit) parameter.

There is an example?

**Comment by shawnmcknight** [comment]
There's no built in pagination functionality if that's what you are asking. I am unaware of any GraphQL implementation which offers that because the GraphQL server is unaware of what the rest of your underlying architecture looks like.

There's no magic to this. You'll need to add pag e and pageSize parameters to your queries and actions and then do something with those parameters inside your actions.
